name: Unit Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up mongodb
      run: |
        echo Setting up mongo
        ./scripts/create_mongo.sh
    - name: Running unit tests
      run: |
        yarn install
        yarn test
